---
name: SmartNUT
version: "0.1"
slug: smartnut
description: Smartly manage battery backup (UPS) devices
url: https://github.com/aquette/addon-smartnut
startup: system
arch:
  - aarch64
  - amd64
  - armv7
services:
  - mqtt:want
init: false
uart: true
udev: true
usb: true
hassio_api: true
hassio_role: manager
homeassistant_api: true
map:
  - addon_config:rw
options:
  autoconf_usb_devices: true
  manually_edit_devices: false
  devices: []
  mqtt:
      - server: ""
      - user: ""
      - password: ""
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  autoconf_usb_devices: bool?
  manually_edit_devices: bool?
  devices:
    - name: str?
      driver: str?
      port: str?
      powervalue: int?
      config:
        - str?
  mqtt:
      - server: str?
      - ca: str?
      - key: str?
      - cert: str?
      - user: str?
      - password: str?
  enable_simulated_device: bool?
  autoconf_remote_nut_devices: bool?
